name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: radianceobi
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag radianceobi/llama-test && docker push radianceobi/llama-test
